[env]
GIT_CLIFF_CONFIG = "{{ config_root }}/.github/cliff.toml"

[tools]
go = "1.27.1"
gh = "2.98.0"
uv = "0.12.10"
git-cliff = "2.13.1"
"pipx:mkdocs" = { version = "1.6.1", uvx_args = "--with mkdocs-material" }

[tasks.init]
run = "go get"

[tasks.test]
run = "go test ./..."

[tasks.build]
run = "go build"

[tasks.release]
file = ".github/release.sh"

[tasks."docs:build"]
dir = "{{ config_root }}/docs"
run = "mkdocs build"

[tasks."docs:start"]
dir = "{{ config_root }}/docs"
run = "mkdocs serve"

[tasks."docs:deploy"]
dir = "{{ config_root }}/docs"
run = "mkdocs gh-deploy --force"
